<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavi-PC" name="Temenos" tests="6" failures="1" timestamp="9 Jan 2018 10:06:00 GMT" time="674.883" errors="0">
  <testcase name="TC_TCIB_PAYMENT_001" time="95.305" classname="com.temenos.testscripts.PaymentTest"/>
  <testcase name="TC_TCIB_PAYMENT_002" time="85.924" classname="com.temenos.testscripts.PaymentTest"/>
  <testcase name="TC_TCIB_PAYMENT_003" time="82.872" classname="com.temenos.testscripts.PaymentTest"/>
  <testcase name="TC_TCIB_PAYMENT_010" time="118.706" classname="com.temenos.testscripts.PaymentTest"/>
  <testcase name="TC_TCIB_PAYMENT_011" time="105.495" classname="com.temenos.testscripts.PaymentTest"/>
  <testcase name="TC_TCIB_PAYMENT_012" time="133.952" classname="com.temenos.testscripts.PaymentTest">
    <failure type="java.lang.AssertionError" message="Actual : Test Failed. Check the steps above in red color.">
      <![CDATA[java.lang.AssertionError: Actual : Test Failed. Check the steps above in red color.
	at org.testng.Assert.fail(Assert.java:94)
	at com.temenos.support.Log.fail(Log.java:554)
	at com.temenos.support.Log.testCaseResult(Log.java:250)
	at com.temenos.testscripts.PaymentTest.TC_TCIB_PAYMENT_012(PaymentTest.java:878)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_TCIB_PAYMENT_012 -->
</testsuite> <!-- Temenos -->
